<script lang="ts" setup></script>

<template>
  <div class="section">
    <div class="clamp content is-size-5">
      <h2 class="title is-2">ARDAC is a home for alive data</h2>
      <p>
        The Arctic Data Collaborative (ARDAC) is a data service that provides
        access and analysis for Arctic data and interactive tools. ARDAC is not
        a data archive. Instead of simply serving raw data, it offers vetted and
        pre-processed datasets to streamline visualization and further
        processing of data, and allow for faster research discovery.
      </p>
      <p>
        We&rsquo;re hosting an extensive catalog of curated Arctic-specific
        data, the majority of which has been collected and generated by
        University of Alaska researchers. By building capacity for those same
        researchers to access and develop technologies that meet the growing
        needs of a changing Arctic we're also seeking to mitigate the
        competitive disadvantage of those very same researchers in proposal
        submissions by putting the supporting infrastructure at their
        fingertips.
      </p>
      <div class="title is-4">ARDAC brings people and data together</div>
      <p>
        We are making data more usable and alive for
        people who need it. ARDAC has been constructed
        thanks to the hard work of <a href="people">our research collaborators</a> and the support of
        the
        <a href="https://science.osti.gov/ber/Research/eessd/Data-Management"
          >Data Management Program</a
        >, US Department of Energy.
      </p>
      <div class="title is-4">License</div>
      <p>
        Unless otherwise specified by source providers, all data available
        through this tool are available through the
        <a href="https://creativecommons.org/licenses/by/4.0/"
          >Creative Commons Attribution 4.0 International (CC by 4.0).</a
        >
      </p>
      <div class="title is-4">Rasdaman raster database</div>
      <p>
        This tool uses the <a href="http://www.rasdaman.org/">rasdaman</a> array
        database management system. This technology enables our team to store,
        analyze and visualize the climate data that are presented through this
        interface. We wish to thank the rasdaman project and team for their
        inspiration and support, and for providing this important innovation in
        data technology.
      </p>
    </div>
  </div>
</template>
<style scoped></style>
