type Slug =
	| 'future-precipitation-map'
	| 'degree-days-projected-statewide'
	| 'flammability-vegetation-current-conditions'
	| 'northern-climate-reports'
	| 'historical-sea-ice-atlas'
	| 'era-access-cds-api'
	| 'arctic-eds'
	| 'permafrost-observations-modeled-air-temp'
	| 'querying-daymet-daily-precipitation'
	| 'modeled-future-flammability'
	| 'historical-nrt-wildfire'
	| 'projected-permafrost-and-magt'
	| 'precipitation-frequency-chart'
	| 'temperature-chart'
	| 'precipitation-chart'
	| 'heating-degree-days-chart'
	| 'freezing-index-chart'
	| 'thawing-index-chart'
	| 'very-cold-day-threshold-chart'
	| 'very-hot-day-threshold-chart'
	| 'summer-days-chart'
	| 'deep-winter-days-chart'
	| 'warm-spell-duration-index-chart'
	| 'cold-spell-duration-index-chart'

