<script lang="ts" setup></script>

<template>
  <div class="section">
    <div class="content is-size-5">
      <h2 class="title is-2">ARDAC is a home for alive data</h2>

        <p>The Arctic Data Collaborative (ARDAC) is a data service that provides access and analysis for Arctic data and interactive tools. ARDAC is not a data archive. Instead of simply serving raw data, it offers vetted and pre-processed datasets to streamlines visualization and further processing of data, and allow for faster research discovery.
      </p>
      <p> We're hosting an extensive catalog of curated Arctic-specific data, the majority of which has been collected and generated by UAF researchers. By building capacity for those same researchers to access and develop technologies that meet the growing needs of a changing Arctic we're also seeking to mitigate the competitive disadvantage of those very same researchers in proposal submissions by putting the supporting infrastructure at their finger tips.</p>
      <p>The QA and QC is complete, the preprocessing and packaging is done, and the capacity for narrative and context is extensive.</p>
      <p>Through partnership with data users, researchers, storytellers, and other collaborators we're increasing transparency to climate data for the North.
      </p>
      <div class="title is-4">
        ARDAC brings people and data together
      </div>
      <p>We are making data more usable and alive for <a href='people'>people</a> that need it.</p>
      <p>
        ARDAC has been constructed thanks to the hard work of our research collaborators and the support of XXXXXXXXXXXXX.
      </p>


  </div>
  </div>
</template>
<style scoped></style>
